# Generated by Django 4.2.11 on 2025-02-12 15:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('helpdesk', '0019_ticket_signed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='documents',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_staff',
            field=models.ManyToManyField(blank=True, related_name='events_part_of', to=settings.AUTH_USER_MODEL, verbose_name='Event staff'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='staff_attending',
            field=models.ManyToManyField(blank=True, related_name='events_attending', to=settings.AUTH_USER_MODEL, verbose_name='Staff attending'),
        ),
    ]
