# Generated by Django 4.2.11 on 2025-02-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0020_ticket_documents_ticket_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ending_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='starting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
